apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-gateway.fullname" . }}
  labels:
    {{- include "auth-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "auth-gateway.serviceAccountName" . }}
      containers:
        - name: {{ include "auth-gateway.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          {{- if or .Values.config.enabled .Values.secrets.enabled }}
          envFrom:
            {{- if .Values.config.enabled }}
            - configMapRef:
                name: {{ include "auth-gateway.fullname" . }}-config
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ include "auth-gateway.fullname" . }}-secret
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30


