{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-gateway.fullname" . }}-secret
  labels:
    {{- include "auth-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}


