spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: ${REDIS_COMMAND_TIMEOUT:2000} # redis-server 호출 했을 때 대기 시간
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:2000} # redis-server 연결시 대기 시간

  cloud:
    gateway:
      httpclient:
        connect-timeout: ${GATEWAY_CONNECT_TIMEOUT:2000}
        response-timeout: ${GATEWAY_RESPONSE_TIMEOUT:10s}
      server:
        webflux:
          routes:
            - id: product-service
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/api/v1/product/**,/api/v1/category/**,/api/v1/stock/**,/api/files/**,/api/v1/reviews/**
            - id: product-service-health
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/health/product
              filters:
                - SetPath=/actuator/health

            - id: order-service
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/api/v1/orders/**,/api/v1/carts/**,/api/v1/delivery/**
            - id: order-service-health
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/health/order
              filters:
                - SetPath=/actuator/health

            - id: user-service
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/v1/users/**
            - id: user-service-health
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/health/user
              filters:
                - SetPath=/actuator/health

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL}
              predicates:
                - Path=/api/v1/payments/**
            - id: payment-service-health
              uri: ${PAYMENT_SERVICE_URL}
              predicates:
                - Path=/health/payment
              filters:
                - SetPath=/actuator/health

            # dev용 내부 라우트
            - id: user-service-dev
              uri: http://user-service:8080
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1

            - id: order-service-dev
              uri: http://order-service:8080
              predicates:
                - Path=/order-service/**
              filters:
                - StripPrefix=1

            - id: product-service-dev
              uri: http://product-service:8080
              predicates:
                - Path=/product-service/**
              filters:
                - StripPrefix=1

            - id: payment-service-dev
              uri: http://payment-service:8080
              predicates:
                - Path=/payment-service/**
              filters:
                - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
          jwk-set-uri: ${OAUTH_JWK_SET_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      otlp:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT_METRICS:http://otel-collector:4317}
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_TRACING:http://otel-collector:4317}

logging:
  level:
    io.opentelemetry.exporter: INFO

security:
  jwt:
    audience: ${OAUTH_AUDIENCE}
