apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
type: Opaque
stringData:
  OAUTH_ISSUER_URI: "${OAUTH_ISSUER_URI}"
  OAUTH_JWK_SET_URI: "${OAUTH_JWK_SET_URI}"
  OAUTH_AUDIENCE: "${OAUTH_AUDIENCE}"

  REDIS_PASSWORD: "${REDIS_PASSWORD}"
